name: 'Conductor Code Review'
description: 'Automatically review pull requests with Conductor'
branding:
  icon: 'eye'
  color: 'blue'
author: 'Conductor Team'

inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}

runs:
  using: 'docker'
  image: 'docker://ghcr.io/conductor-codes/conductor:latest'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
