name: 'Conductor Code Review'
description: 'Automatically review pull requests with Conductor'
branding:
  icon: 'eye'
  color: 'blue'
author: 'Conductor Team'

inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  conductor_llm_config:
    description: 'LLM configuration properties for Conductor (JSON object)'
    required: true
  conductor_api_key:
    description: 'Conductor API Key credentials'
    required: true

runs:
  using: 'docker'
  image: 'docker://ghcr.io/conductor-codes/conductor:latest'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    CONDUCTOR_LLM_CONFIG: ${{ inputs.conductor_llm_config }}
    CONDUCTOR_API_KEY: ${{ inputs.conductor_api_key }}
